### ISSUE TITLE
FetLife ASL Search (Extended Edition) no results

### ISSUE THREAD

**Issue by tdbdk** [meitar/fetlife-aslsearch#20] opened 2015-11-02 15:08 UTC
I am using FetLife ASL Search (Extended Edition) on a very "simple" search, but i get no results - nomatter what criteria i use. When I use the slow search, it does give me some results, but way fewer then i find if i just search for it myself. What am I doing wrong?

**Comment by tdbdk** [comment] 2015-11-04 09:42
Is the script not working or?? Please help??

I wanted to donate, but honestly, i would like to see it working first.

**Comment by meitar** [comment] 2015-11-05 18:50
Dupe of #18.

**Closed by meitar** 2015-11-05 18:50 UTC
Labels: duplicate
