### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by DRSteven** [meitar/fetlife-aslsearch#37] opened 2017-08-24 14:30 UTC
Hi, I'm hoping this script is still maintained?

I'm testing this in Tor Browser 7.0.4 (based on Mozilla Firefox 52.3.0) (32-bit)
I don't see the A/S/L box on top of the page.
image: https://preview.ibb.co/nidkGk/fl.png

I found a direct link somewhere (just to test): https://script.google.com/macros/s/AKfycbxjpuCSz9uam23hztGYyiE6IbHX22EGzhq7fN4jQGo1jiRp520/exec?embedded=true
when I use that, I can select all my search options, but it never returns any results

am I doing something wrong, or can I provide you with more details to debug?

**Comment by meitar** [comment] 2017-08-24 17:36
Duplicate of #18.

**Closed by meitar** 2017-08-24 17:36 UTC
Labels: duplicate
