### ISSUE TITLE
Screen Frozen

### ISSUE THREAD

**Issue by Anderson-David-1981** [meitar/fetlife-aslsearch#33] opened 2016-09-27 04:00 UTC
The search screen is frozen after the progress bar finishes - no results and just stays blank if I close the dialogue or click on "maybe later"
![error](https://cloud.githubusercontent.com/assets/22463757/18859791/67d17338-8445-11e6-8afb-3614b44d000b.jpg)

**Comment by forkenbrock** [comment] 2016-10-15 02:05
I have this same issue.  The tool does not work in Firefox or Chrome.

**Comment by Anderson-David-1981** [comment] 2016-10-16 18:23
Is it available for Internet Explorer or another browser?

**Comment by Anderson-David-1981** [comment] 2016-12-16 17:37
Where DOES the tool work, if at all, please?

**Comment by EvilGamerX** [comment] 2017-06-04 19:26
I can confirm that this is still a thing if anyone is actually still working on this project.

**Comment by meitar** [comment] 2017-06-04 22:36
Duplicate of #18.

**Closed by meitar** 2017-06-04 22:36 UTC
