### ISSUE TITLE
Extended edition not displaying results well/not showing accurate information.

### ISSUE THREAD

**Issue by ImBrianHello** [meitar/fetlife-aslsearch#5] opened 2015-06-13 14:41 UTC
Results do not show up in the same ascending order as the classic search. Shows random order with many no-activity profiles without photos even after filtering the results by number of photos.

Filtering number of photos doesn't not work fully. Many profiles with at least one photo don't show as having any photos in the results.

**Comment by meitar** [comment] 2015-06-13 17:01
Dupe of #7.

**Closed by meitar** 2015-06-13 17:01 UTC
Labels: duplicate, invalid
