### ISSUE TITLE
Extended ASL Search Not Working

### ISSUE THREAD

**Issue by shyam821** [meitar/fetlife-aslsearch#23] opened 2015-11-10 17:16 UTC
Dear Meitar,
                           Firstly compliments for a good initiative to help us kinksters :). My issue is that, when I hit the "Extended ASL search" tab a google script page opens independently. In this script page I get to see the neatly stacked options and categories of filtering out profiles. When I am done with the inputs and hit the search tab on the lower left side a search ribbon starts to load, it progresses from the left to end in the right, presumably indicating the process is done. But the problem is that after the blue ribbon reaches the 100% ceiling I see no change, no results coming up. Just the Blue-White striped ribbon running endlessly. My OS is XP SP3 and my browser is FireFox 42.0 and my Greasemonkey version is 3.4 Beta 1. The structure of the script with so many useful options looks juicy, but not able to see any results. Meitar please help in what can be done.

Thanks & Regards,
Shyam

**Comment by meitar** [comment] 2015-11-10 17:19
Dupe of #18.

**Closed by meitar** 2015-11-10 17:19 UTC

**Comment by shyam821** [comment] 2015-11-11 05:11
So waht.. there are no solutions!

**Comment by shyam821** [comment] 2015-11-11 05:13
I just labels of Dupes 18,20,21 but no solution!

**Comment by shyam821** [comment] 2015-11-11 05:15
how can it be closed without any solution :O
