### ISSUE TITLE
FetLife ASL Search (Extended Edition) loads nothing

### ISSUE THREAD

**Issue by tdbdk** [meitar/fetlife-aslsearch#21] opened 2015-11-04 10:22 UTC
I followed the installation guide and opened fetlife. The classical (slow) search is able to return a few hits, but when i open FetLife ASL Search (Extended Edition) and make a VERY wide search, nothing happens. Is just says "loading..." and nothing happens. I started it two hours ago.

**Comment by meitar** [comment] 2015-11-04 19:57
Dupe of #20 .

**Closed by meitar** 2015-11-04 19:57 UTC
Labels: duplicate
