### ISSUE TITLE
Is This No Longer Being Supported?

### ISSUE THREAD

**Issue by bluehatter** [meitar/fetlife-aslsearch#45] opened 2018-02-05 09:12 UTC
Hello. I was just curious if this ASL search is no longer being supported? The search feature hasn't been working for me for quite some time but things seem pretty quiet here. If this is no longer being supported, does anyone know of some other ASL search that works for Fetlife? I got a lot of use out of this and was able to make some friends with it, so I found it to be very useful.

**Comment by meitar** [comment] 2018-02-05 16:41
Duplicate of #18.

**Closed by meitar** 2018-02-05 16:41 UTC
