### ISSUE TITLE
ASL 0.4.6 Classic search results overlaid on page, hard to read

### ISSUE THREAD

**Issue by MuviaGT** [meitar/fetlife-aslsearch#32] opened 2016-06-23 17:07 UTC
Hi there,

Thank you for your hard work on this. It seems plenty of people are very happy users but for it I can't get it to work. 

I've tried both the Chrome and Firefox solution with both having the latest versions but I receive no results. The status bar turns blue and stays that way for several hours.

Classic search does show results but they are overlayed on the original page making it very hard to read.

Kind regards,
Muvia

**Comment by meitar** [comment] 2016-06-23 22:35
> Classic search does show results but they are overlayed on the original page making it very hard to read.

That sounds like a new bug. Can you send a screenshot? Thanks.

**Comment by meitar** [comment] 2016-06-24 03:55
Issue might also be related to or a duplicate of #31.

**Comment by MuviaGT** [comment] 2016-06-24 07:54
It indeed
![capture](https://cloud.githubusercontent.com/assets/20114132/16331603/adac4e9e-39f1-11e6-803a-25204385d086.JPG)
 seems like a similar problem as #31 however, its on top this time

**Comment by meitar** [comment] 2017-08-24 17:37
Duplicate of #31.

**Closed by meitar** 2017-08-24 17:37 UTC
