### ISSUE TITLE
Extended A/S/L search won't load in Firefox

### ISSUE THREAD

**Issue by Numberphile** [meitar/fetlife-aslsearch#9] opened 2015-06-30 00:24 UTC
Date:    6/29/2015       
Reported By:   Numberphile

Product:   Fetlife A/S/L search Extended         Version: 0.4.4
Platform:  Greasemonkey                                Version:  3.2
Browser:  Firefox                                              Version:  38.0.5
URL:        

Is it reproducible: Yes

Description
===========
Identical to the image from #8, I can see the checkbox, I open it, but the advanced A/S/L search is just a blank rectangle.

The "Classic Search" does open but is slower than it used to be.

Steps to Produce/Reproduce
--------------------------
Download Firefox
Download Greasemonkey
Click install link for A/S/L search  "Download and install FetLife Age/Sex/Location Search" https://github.com/meitar/fetlife-aslsearch/raw/master/fetlife-age-sex-location-search.user.js
Login to FL account
(All versions are up to date as of half an hour ago)

Expected Results
----------------
It should work

Actual Results
--------------
It doesn't work

Workarounds
-----------
Tried copying the "Server" folder & contents into the containing folder for the script, didn't work.

Attachments
-----------

Other Information
-----------------
I think this is an installation problem. After installing as described there are only two files in the GM folder, 
fetlife-age-sex-location-search.user.js 
jquery-2.1.4.min

I searched for the string "Choose a minimum and maximum age" but didn't find it in these files. (In the old version everything was contained in one js file)

I did find this string in the "search-form.html" file on this website.... which makes sense except I have no clue how to install it.

If search-form.html and the other files under "server" are needed to run the script (and it seems very likely they are) I just need to know where to put em/ how to install them.

I appreciate any help you can give, I've been using the old A/S/L script for a while and think it's great.

Thank you,
-Numberphile

**Comment by meitar** [comment] 2015-06-30 03:25
I have the exact same setup described above (Firefox 38.0.5, Greasemonkey 3.2, and FetLife ASL Search 0.4.4). I uninstalled everything, reinstalled everything, and still can not reproduce this problem.

> I think this is an installation problem. After installing as described there are only two files in the GM folder,
> fetlife-age-sex-location-search.user.js
> jquery-2.1.4.min

Nope, that's actually exactly what's expected to be in your Greasemonkey folder. (The installation seems to be fine. If you want to be doubly sure that the installation is fine, [check the integrity of those two files using a hash](https://web.archive.org/web/20150516001610/https://support.apple.com/en-us/HT201259). you should have the following `shasum`s of the files: `jquery-2.1.4.min` should be `43dc554608df885a59ddeece1598c6ace434d747` and `fetlife-age-sex-location-search.user.js` should be `68e0147182de0cfcf50eb9ff2079b2dbf05ece84`.)

Other information that is missing from your bug report that might be helpful would include:

* Your computer's operating system. (Windows, Mac, Linux, the version, the model, etc.)
* A list of other userscripts installed in your Greasemonkey, if any.
* A list of other add-ons installed in your Firefox, if any.
* The configuration of your Firefox's security (SSL/TLS) and network preferences.
* A list of any other software on your system that you know or believe to be interacting with your web browsing traffic (anti-virus scanners, firewalls, etc)
* More information about your network and geographic location; does the issue happen on a home Internet connection, a business Internet connection, both? Are some websites blocked/censored by your Internet service provider? That sort of thing.

You're not the only one having this problem but, unfortunately, I have experienced absolutely none of the problems described and so I don't really know how to approach resolving the issue because the issue doesn't exist for me. It's certainly not a Firefox/Greasemonkey/script issue,

**Comment by Numberphile** [comment] 2015-06-30 06:15
Specs:

Vista 32 bit, SP2  (Fresh install of my OS about a week ago)
No other userscripts on GM / No other add-ons (just reinstalled Firefox)
All Firefox settings are default, (I think running TLS 1.2?)
Norton Anti Virus
Home Internet connection in the US, nothing relevant blocked by ISP that I know of

Here's some output from the console...

This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] analytics.js
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] ecommerce.js
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] collect
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] collect
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it. adgear_iframe_1_dark.html
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] exec
Load denied by X-Frame-Options: https://script.google.com/macros/s/AKfycbxjpuCSz9uam23hztGYyiE6IbHX22EGzhq7fN4jQGo1jiRp520/exec?embedded=true does not permit cross-origin framing. <unknown>
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More]    eade0ff4c8


This one was interesting:

 Load denied by X-Frame-Options: https://script.google.com/macros/s/AKfycbxjpuCSz9uam23hztGYyiE6IbHX22EGzhq7fN4jQGo1jiRp520/exec?embedded=true does not permit cross-origin framing. <unknown>

When I went to the site listed I saw the missing frame <<http://i.imgur.com/PWaZAby.jpg>>, it was even functional except it didn't give any results.

**Comment by meitar** [comment] 2015-06-30 07:17
I wonder if the combination of Vista and Firefox is causing the "Load denied" message. I'm running a Mac, and I don't see that message. I'll look into it when I have a moment.

Meanwhile, what do you mean "it didn't give any results"? I get plenty of results for most searches.

**Comment by Numberphile** [comment] 2015-06-30 07:57
I think I was being sloppy- tried again with a much broader search and it gave plenty of results. I'll play around with the search parameters a bit more tomorrow.

**Comment by meitar** [comment] 2015-06-30 15:50
Regarding the "Load denied," can you please go to [this test page](http://www.enhanceie.com/test/clickjack/) and provide a full-page screenshot of the results? Thanks.

**Comment by Numberphile** [comment] 2015-06-30 17:08
Sure thing, here's an album of the whole page: <<http://imgur.com/a/eomKi>>

**Comment by JayKeelz** [comment] 2015-07-01 16:32
I'm pretty sure the issue is due to the option to DENY external FRAME BUSTING... which is what the javascript is attempting to do?

**Comment by meitar** [comment] 2015-07-01 19:49
@JayKeelz , yes, the issue is certainly related to the `X-Frame-Options` HTTP header, but what's curious is that Firefox on Mac OS X (despite having the exact same results as @Numberphile 's screenshots) displays the `<iframe>` contents whereas the same version of Firefox on (several different versions of) Windows seems to honor the X-Frame-Options's `DENY` value. I'm not sure why there's the difference between Firefox's behavior; Google Chrome on both Mac and Windows hosts seems to behave consistently.

I might just change the behavior of the script to do for Firefox what already happens in Google Chrome (i.e., simply open in a new window, directly, rather than have the server code framed), but I'd still like to know why the difference in Firefox's behavior based on the OS used. It seems like a bug in the browser to me, actually. Hmm.

**Comment by Numberphile** [comment] 2015-07-02 00:51
Meitar, just want to say thanks for all your help on this, I agree it must be either a Firefox bug or a "Vista is altering how Firefox works" sort of thing. Using the server link to search works. (I played around with the search criteria and the "it's not giving any results" thing was just me making the search too narrow, duh.)

For anyone else coming here and having this particular bug on Firefox... here is the raw link to the "Extended Search" , just exactly what you would see in the frame.

https://script.google.com/macros/s/AKfycbxjpuCSz9uam23hztGYyiE6IbHX22EGzhq7fN4jQGo1jiRp520/exec?embedded=true

**Comment by meitar** [comment] 2015-07-07 09:03
Hi, I haven't had enough time to thoroughly research this issue so I've provided a workaround specific to Windows computers (which seems to be the commonality in all failure cases). Before I release this publicly, however, I would greatly appreciate it if you could [install the test version of this script by clicking here](https://github.com/meitar/fetlife-aslsearch/raw/754586c8b40e4afd1e072c5b7ffd7c4dfc3eb6bf/fetlife-age-sex-location-search.user.js) and letting me know if it works for you. If it does, I'll release the update to the master branch so other users will be able to auto-update. Thanks for your help in testing this fix.

**Comment by Numberphile** [comment] 2015-07-07 13:50
Yup, that works for me. And glad I could help.

**Closed** 2015-07-07 17:17 UTC
Labels: bug
