### ISSUE TITLE
doesn't work anymore?

### ISSUE THREAD

**Issue by Rubberdiver** [meitar/fetlife-aslsearch#24] opened 2015-11-30 11:59 UTC
Hi, I tried it with latest Firefox and latest Greasemonkey, no luck. The Search goes on forever and doesn't delivers any profiles, not the new nor the old method.

Any help? Did they finally shut it off?

**Comment by meitar** [comment] 2015-11-30 12:05
Dupe of #18.

**Closed by meitar** 2015-11-30 12:05 UTC
Labels: duplicate
