### ISSUE TITLE
Why there is not all the results

### ISSUE THREAD

**Issue by prisonier2** [meitar/fetlife-aslsearch#16] opened 2015-07-27 09:08 UTC
Hello,

When I'm looking for women under 25 in France with S-type, I get 19 results ....

The old ASL gabe me dozens of results.

Thanks

**Comment by meitar** [comment] 2015-07-27 17:13
Dupe of #7.

**Closed by meitar** 2015-07-27 17:13 UTC
Labels: duplicate

**Comment by ImBrianHello** [comment] 2015-07-27 19:18
To OP: It never worked right for me either. I use the classic search.

**Comment by adarklake** [comment] 2015-07-27 19:59
Does the classic search risk you being banned?

**Comment by meitar** [comment] 2015-07-29 21:05
> Does the classic search risk you being banned?

Yes, but you can use the stealthiness slider to decrease the risk of that.
