### ISSUE TITLE
No results returned, layout needs an update.

### ISSUE THREAD

**Issue by deanpr** [meitar/fetlife-aslsearch#50] opened 2019-02-05 20:18 UTC
In previous issues it's already mentioned that due Fetlife design changes the alssearch was not showing properly anymore. Despite the layout issues the classic search was still working. However, the classic search stopped working since a few days. Due changes from Fetlife it seems like the script can't connect to the database anymore ending up in an endless search..... with no results. @meitar it would be awesome if you could an update and revive the script.

**Comment by meitar** [comment] 2019-02-05 20:38
Duplicate of #18.

**Closed by meitar** 2019-02-05 20:38 UTC

**Comment by deanpr** [comment] 2019-02-05 22:16
@meitar as you wrote in #18:
> For those of you having trouble with the "Classic" search mode, you should update to the newest version (0.4.5, released today). This also fixes #27, which some of you have reported here as well.

Updated already to version 0.4.6 a long time ago. Extended search didn't work anymore for years. However, classic search did still work again after the 0.4.5 update until a few days ago, I guess Fetlife changed something in the last few days and this is a new issue.

**Comment by alexfreeaccount** [comment] 2019-04-25 10:02
As of 26.4.19 I'm having the same issue that Extended search has no functionality, and classic search ceased functioning around February of 2019. Is this the same experience of others, and is there a fix?
