### ISSUE TITLE
Fetlife Design Change

### ISSUE THREAD

**Issue by Slofe** [meitar/fetlife-aslsearch#49] opened 2019-02-02 23:45 UTC
I get this is a duplicate issue and I'm sure you've long abandoned this script but thought I'd bring to your attention that the classic search no longer returns any results. Fetlife changed something recently, the layout looks different in some areas and the script no longer works.

**Comment by meitar** [comment] 2019-02-03 01:55
Duplicate of #46.

**Closed by meitar** 2019-02-03 01:55 UTC
