### ISSUE TITLE
Problem loading

### ISSUE THREAD

**Issue by canthinkofagoodusername** [meitar/fetlife-aslsearch#25] opened 2015-12-13 17:27 UTC
As has been mentioned by many other people here already I greatly appreciate your work in creating this tool and would love to donate to help out on future projects.  However, the current issue of the loading bar which stays blue and never fully loads is a problem which makes using fetlife ASL impossible at the moment; is this simply an insurmountable issue or is there any possibility of ASL working again in the future?  Thanks again Meitar!

**Comment by meitar** [comment] 2015-12-13 19:49
Dupe of #18.

**Closed by meitar** 2015-12-13 19:49 UTC
Labels: duplicate
