### ISSUE TITLE
I can see the A/S/L checkbox, I click it, the panel opens, but it is blank.

### ISSUE THREAD

**Issue by chrisstorrer** [meitar/fetlife-aslsearch#8] opened 2015-06-28 17:19 UTC
I can only do the classic search in firefox. If I click on the extended search tab it is blank space between where the search options should be.
![asl in firefox](https://cloud.githubusercontent.com/assets/13088830/8397411/26481422-1d7f-11e5-8a7a-5f71eb0cc4d8.png)

**Comment by meitar** [comment] 2015-06-28 22:59
This is a dupe of #6. As I mentioned there:

> I can't reproduce this issue. Opening in a new tab in Chrome is intended behavior, so that's not a bug. Not loading in Firefox would be a bug, but it does load for me, so I don't know why it's not working for you.
> 
> As per usual, please ensure you're using the latest version of Mozilla Firefox, the latest version of Greasemonkey, and that any other extensions/plugins/user-scripts/etc. are not conflicting with this one.
> 
> If you're still having issues, please read [How to write a good bug report](http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/) and copy the template they provide into the new issue form when filing a [new issue](https://github.com/meitar/fetlife-aslsearch/issues/new) to ensure your bug report is complete and usefully informational.

**Closed by meitar** 2015-06-28 22:59 UTC
Labels: duplicate

**Comment by meitar** [comment] 2015-06-30 15:52
@chrisstorer, out of curiosity, what version of Windows are you running?

**Comment by chrisstorrer** [comment] 2015-07-01 01:09
@meitarmoscovitz I am using Windows 7 Service Pack 1

**Comment by meitar** [comment] 2015-07-01 14:56
Can you please go to [this test page](http://www.enhanceie.com/test/clickjack/) and give me a full-page screenshot of the results?

**Comment by meitar** [comment] 2015-07-07 09:03
Hi, I haven't had enough time to thoroughly research this issue so I've provided a workaround specific to Windows computers (which seems to be the commonality in all failure cases). Before I release this publicly, however, I would greatly appreciate it if you could [install the test version of this script by clicking here](https://github.com/meitar/fetlife-aslsearch/raw/754586c8b40e4afd1e072c5b7ffd7c4dfc3eb6bf/fetlife-age-sex-location-search.user.js) and letting me know if it works for you. If it does, I'll release the update to the master branch so other users will be able to auto-update. Thanks for your help in testing this fix.
